### ISSUE TITLE
node-red startet nicht mehr

### ISSUE THREAD

**Issue by irgendjemand0** [DevNiko/node-red-geofox-api#6]
Moin,
ich bin noch recht neu auf dem Gebiet hier und wollte einen Abfahrtsmonitor mit node-red basteln. Zu meiner Erleichterung gab es schon ein Geofox Plugin für node-red. Dies habe ich also installiert und probiert mich damit erstmal vertraut zu machen. 
Jetzt stürzt aber immer node-red ab und startet gar nicht erst, auch nach neu Installationen kommt noch der selbe Fehler...:
`26 Jul 18:46:20 - [error] TypeError: Cannot read properties of undefined (reading '0')
    at handleDepartures (C:\Users\Julius\.node-red\node_modules\node-red-contrib-geofox-api\geofox-api.js:179:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GeofoxApiNode._inputCallback (C:\Users\Julius\.node-red\node_modules\node-red-contrib-geofox-api\geofox-api.js:258:28)`

Weil der Fehler scheint, als hätte er etwas mit dem Geofox Plugin zu tun, dachte ich ich melde mich erstmal hier.
Wenn jemand eine Idee oder Lösung hat, würde ich mich sehr freuen.

MfG

**Comment by DevNiko** [comment]
Hi @irgendjemand0 ,

welche Node-Red Version hast du im Einsatz?

Ich habe leider, seit längerem, kein Geofox API Account mehr.

Hast du hier die API Credentials eingetragen?

![image](https://user-images.githubusercontent.com/5196588/181092241-d77b2072-7cdb-4e4c-9be3-394dc1ecb758.png)

VG

**Comment by irgendjemand0** [comment]
> Hi @irgendjemand0 ,
> 
> welche Node-Red Version hast du im Einsatz?
> 
> Ich habe leider, seit längerem, kein Geofox API Account mehr.
> 
> Hast du hier die API Credentials eingetragen?
> 
> ![image](https://user-images.githubusercontent.com/5196588/181092241-d77b2072-7cdb-4e4c-9be3-394dc1ecb758.png)
> 
> VG

Ich benutzte Node-Red 3.0.1. Die Zugangsdaten habe ich natürlich eingegeben...

**Comment by irgendjemand0** [comment]
> Hi @irgendjemand0 ,
> 
> 
> 
> welche Node-Red Version hast du im Einsatz?
> 
> 
> 
> Ich habe leider, seit längerem, kein Geofox API Account mehr.
> 
> 
> 
> Hast du hier die API Credentials eingetragen?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/5196588/181092241-d77b2072-7cdb-4e4c-9be3-394dc1ecb758.png)
> 
> 
> 
> VG

Mittlerweile kann ich Node-red garnicht mehr benutzten. Egal wie oft ich deinstallieren oder neu installiere, es kommt immer der Fehler... auch wenn das Plugin gelöscht ist

**Comment by irgendjemand0** [comment]
> Hi @irgendjemand0 ,
> 
> welche Node-Red Version hast du im Einsatz?
> 
> Ich habe leider, seit längerem, kein Geofox API Account mehr.
> 
> Hast du hier die API Credentials eingetragen?
> 
> ![image](https://user-images.githubusercontent.com/5196588/181092241-d77b2072-7cdb-4e4c-9be3-394dc1ecb758.png)
> 
> VG

Ich habe mittlerweile eine eigene http request geschrieben, aber es kommt der Fehler `payload: "{"returnCode":"ERROR_TEXT","errorText":"A technical problem occured while processing your request.","errorDevInfo":"Authentication failed!"}"
`

**Comment by irgendjemand0** [comment]
Also es hat jetzt nicht mehr direkt mit deinem Plugin zu tun, aber könntest du mir vielleicht sagen, wie ich die Signatur aus dem Passwort erstelle? Aus der Anleitung werde ich nicht so richtig schlau...
